project_id = "uykdyqdeyilpulaqlqip"

[functions.create-payment-link]
verify_jwt = true

[functions.handle-razorpay-webhook]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = true

[functions.submit-public-form]
verify_jwt = false

[functions.register-company]
verify_jwt = false

[functions.purchase-licenses]
verify_jwt = true

[functions.handle-license-webhook]
verify_jwt = false

[functions.get-public-form]
verify_jwt = false

[functions.delete-team-member]
verify_jwt = true

[functions.verify-domain]
verify_jwt = false

[functions.admin-manage-company]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.process-auto-debit]
verify_jwt = false

[functions.initiate-wallet-recharge]
verify_jwt = true

[functions.verify-wallet-recharge]
verify_jwt = true

[functions.validate-discount]
verify_jwt = true

[functions.redeem-gift-card]
verify_jwt = true

[functions.purchase-addon]
verify_jwt = true
