project_id = "uykdyqdeyilpulaqlqip"

[functions.create-payment-link]
verify_jwt = true

[functions.handle-razorpay-webhook]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = true

[functions.submit-public-form]
verify_jwt = false

[functions.register-company]
verify_jwt = false

[functions.purchase-licenses]
verify_jwt = true

[functions.handle-license-webhook]
verify_jwt = false

[functions.get-public-form]
verify_jwt = false

[functions.delete-team-member]
verify_jwt = true

[functions.verify-domain]
verify_jwt = false

[functions.admin-manage-company]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true

[functions.process-auto-debit]
verify_jwt = false

[functions.initiate-wallet-recharge]
verify_jwt = true

[functions.verify-wallet-recharge]
verify_jwt = true

[functions.validate-discount]
verify_jwt = true

[functions.redeem-gift-card]
verify_jwt = true

[functions.purchase-addon]
verify_jwt = true

[functions.meta-lead-webhook]
verify_jwt = false

[functions.google-lead-webhook]
verify_jwt = false

[functions.linkedin-lead-webhook]
verify_jwt = false

[functions.change-industry]
verify_jwt = true

[functions.unlock-lead-attributes]
verify_jwt = true

[functions.meta-oauth-callback]
verify_jwt = false

[functions.meta-select-page]
verify_jwt = false

[functions.process-reminders]
enabled = true
verify_jwt = true
import_map = "./functions/process-reminders/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-reminders/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-reminders/*.html" ]
